version: '3.4'

services:
  mongo:
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  banking.operation.receipt.consumer:
    container_name: receipt.consumer
    environment:
      - "Environment=Development"
      - "MongoDatabase:ConnectionString=mongodb://root:example@mongo:27017"
      - "MongoDatabase:DatabaseName=BankingOperation"
      - "MongoDatabase:CollectionName=Receipts"
      - "KafkaParameters:BootstrapServers=broker:9092"
      - "KafkaParameters:Topic=banking.operation-receipt"
      - "KafkaParameters:GroupId=banking.operation-group"
