version: '3.4'

services:
  banking.operation.receipt.consumer:
    image: ${DOCKER_REGISTRY-}bankingoperationreceiptconsumer
    build:
      context: .
      dockerfile: Banking.Operation.Receipt.Consumer.Worker/Dockerfile

  mongo:
    image: mongo

  mongo-express:
    image: mongo-express

networks:
  default:
    external: true
    name: bankingoperation-client-api_backend
